spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_schema: delivery
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/smart-home-tech
    username: test
    password: test

server:
  port: 0
delivery:
  base-cost: 5.0
  fragile-multiplier: 0.2
  weight-multiplier: 0.3
  volume-multiplier: 0.2
  address-difference-multiplier: 0.2